//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.23 at 01:03:19 PM IST 
//


package com.ecb.xmltutility.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CounterpartyIdentification3Choice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CounterpartyIdentification3Choice">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="LEI" type="{urn:iso:std:iso:20022:tech:xs:auth.013.001.02}LEIIdentifier"/>
 *         &lt;element name="SctrAndLctn" type="{urn:iso:std:iso:20022:tech:xs:auth.013.001.02}SectorAndLocation1"/>
 *         &lt;element name="NmAndLctn" type="{urn:iso:std:iso:20022:tech:xs:auth.013.001.02}NameAndLocation1"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CounterpartyIdentification3Choice", propOrder = {
    "lei",
    "sctrAndLctn",
    "nmAndLctn"
})
public class CounterpartyIdentification3Choice {

    @XmlElement(name = "LEI")
    protected String lei;
    @XmlElement(name = "SctrAndLctn")
    protected SectorAndLocation1 sctrAndLctn;
    @XmlElement(name = "NmAndLctn")
    protected NameAndLocation1 nmAndLctn;

    /**
     * Gets the value of the lei property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLEI() {
        return lei;
    }

    /**
     * Sets the value of the lei property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLEI(String value) {
        this.lei = value;
    }

    /**
     * Gets the value of the sctrAndLctn property.
     * 
     * @return
     *     possible object is
     *     {@link SectorAndLocation1 }
     *     
     */
    public SectorAndLocation1 getSctrAndLctn() {
        return sctrAndLctn;
    }

    /**
     * Sets the value of the sctrAndLctn property.
     * 
     * @param value
     *     allowed object is
     *     {@link SectorAndLocation1 }
     *     
     */
    public void setSctrAndLctn(SectorAndLocation1 value) {
        this.sctrAndLctn = value;
    }

    /**
     * Gets the value of the nmAndLctn property.
     * 
     * @return
     *     possible object is
     *     {@link NameAndLocation1 }
     *     
     */
    public NameAndLocation1 getNmAndLctn() {
        return nmAndLctn;
    }

    /**
     * Sets the value of the nmAndLctn property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameAndLocation1 }
     *     
     */
    public void setNmAndLctn(NameAndLocation1 value) {
        this.nmAndLctn = value;
    }

}
