//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.23 at 01:03:19 PM IST 
//


package com.ecb.xmltutility.dto;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FinancialInstrumentProductType1Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FinancialInstrumentProductType1Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CEOD"/>
 *     &lt;enumeration value="COPR"/>
 *     &lt;enumeration value="OTHR"/>
 *     &lt;enumeration value="ABCP"/>
 *     &lt;enumeration value="FRNT"/>
 *     &lt;enumeration value="CACM"/>
 *     &lt;enumeration value="DPST"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FinancialInstrumentProductType1Code")
@XmlEnum
public enum FinancialInstrumentProductType1Code {

    CEOD,
    COPR,
    OTHR,
    ABCP,
    FRNT,
    CACM,
    DPST;

    public String value() {
        return name();
    }

    public static FinancialInstrumentProductType1Code fromValue(String v) {
        return valueOf(v);
    }

}
