//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.23 at 01:03:19 PM IST 
//


package com.ecb.xmltutility.dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MoneyMarketUnsecuredMarketStatisticalReportV02 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MoneyMarketUnsecuredMarketStatisticalReportV02">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RptHdr" type="{urn:iso:std:iso:20022:tech:xs:auth.013.001.02}MoneyMarketReportHeader1"/>
 *         &lt;element name="UscrdMktRpt" type="{urn:iso:std:iso:20022:tech:xs:auth.013.001.02}UnsecuredMarketReport4Choice"/>
 *         &lt;element name="SplmtryData" type="{urn:iso:std:iso:20022:tech:xs:auth.013.001.02}SupplementaryData1" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MoneyMarketUnsecuredMarketStatisticalReportV02", propOrder = {
    "rptHdr",
    "uscrdMktRpt",
    "splmtryData"
})
public class MoneyMarketUnsecuredMarketStatisticalReportV02 {

    @XmlElement(name = "RptHdr", required = true)
    protected MoneyMarketReportHeader1 rptHdr;
    @XmlElement(name = "UscrdMktRpt", required = true)
    protected UnsecuredMarketReport4Choice uscrdMktRpt;
    @XmlElement(name = "SplmtryData")
    protected List<SupplementaryData1> splmtryData;

    /**
     * Gets the value of the rptHdr property.
     * 
     * @return
     *     possible object is
     *     {@link MoneyMarketReportHeader1 }
     *     
     */
    public MoneyMarketReportHeader1 getRptHdr() {
        return rptHdr;
    }

    /**
     * Sets the value of the rptHdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link MoneyMarketReportHeader1 }
     *     
     */
    public void setRptHdr(MoneyMarketReportHeader1 value) {
        this.rptHdr = value;
    }

    /**
     * Gets the value of the uscrdMktRpt property.
     * 
     * @return
     *     possible object is
     *     {@link UnsecuredMarketReport4Choice }
     *     
     */
    public UnsecuredMarketReport4Choice getUscrdMktRpt() {
        return uscrdMktRpt;
    }

    /**
     * Sets the value of the uscrdMktRpt property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnsecuredMarketReport4Choice }
     *     
     */
    public void setUscrdMktRpt(UnsecuredMarketReport4Choice value) {
        this.uscrdMktRpt = value;
    }

    /**
     * Gets the value of the splmtryData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the splmtryData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSplmtryData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupplementaryData1 }
     * 
     * 
     */
    public List<SupplementaryData1> getSplmtryData() {
        if (splmtryData == null) {
            splmtryData = new ArrayList<SupplementaryData1>();
        }
        return this.splmtryData;
    }

}
