//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.23 at 01:03:19 PM IST 
//


package com.ecb.xmltutility.dto;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.xsd.javaclass package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AppHdr_QNAME = new QName("urn:iso:std:iso:20022:tech:xs:head.001.001.01", "AppHdr");
    private final static QName _MMSRMessage_QNAME = new QName("", "MMSRMessage");
    private final static QName _Document_QNAME = new QName("urn:iso:std:iso:20022:tech:xs:auth.013.001.02", "Document");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.xsd.javaclass
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DateAndDateTimeChoice }
     * 
     */
    public DateAndDateTimeChoice createDateAndDateTimeChoice() {
        return new DateAndDateTimeChoice();
    }

    /**
     * Create an instance of {@link DateTimePeriod1 }
     * 
     */
    public DateTimePeriod1 createDateTimePeriod1() {
        return new DateTimePeriod1();
    }

    /**
     * Create an instance of {@link ClearingSystemIdentification2Choice }
     * 
     */
    public ClearingSystemIdentification2Choice createClearingSystemIdentification2Choice() {
        return new ClearingSystemIdentification2Choice();
    }

    /**
     * Create an instance of {@link SectorAndLocation1 }
     * 
     */
    public SectorAndLocation1 createSectorAndLocation1() {
        return new SectorAndLocation1();
    }

    /**
     * Create an instance of {@link SupplementaryDataEnvelope1 }
     * 
     */
    public SupplementaryDataEnvelope1 createSupplementaryDataEnvelope1() {
        return new SupplementaryDataEnvelope1();
    }

    /**
     * Create an instance of {@link UnsecuredMarketReport4Choice }
     * 
     */
    public UnsecuredMarketReport4Choice createUnsecuredMarketReport4Choice() {
        return new UnsecuredMarketReport4Choice();
    }

    /**
     * Create an instance of {@link GenericOrganisationIdentification1 }
     * 
     */
    public GenericOrganisationIdentification1 createGenericOrganisationIdentification1() {
        return new GenericOrganisationIdentification1();
    }

    /**
     * Create an instance of {@link UnsecuredMarketTransaction4 }
     * 
     */
    public UnsecuredMarketTransaction4 createUnsecuredMarketTransaction4() {
        return new UnsecuredMarketTransaction4();
    }

    /**
     * Create an instance of {@link GenericPersonIdentification1 }
     * 
     */
    public GenericPersonIdentification1 createGenericPersonIdentification1() {
        return new GenericPersonIdentification1();
    }

    /**
     * Create an instance of {@link FinancialIdentificationSchemeName1Choice }
     * 
     */
    public FinancialIdentificationSchemeName1Choice createFinancialIdentificationSchemeName1Choice() {
        return new FinancialIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link OrganisationIdentificationSchemeName1Choice }
     * 
     */
    public OrganisationIdentificationSchemeName1Choice createOrganisationIdentificationSchemeName1Choice() {
        return new OrganisationIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link MoneyMarketReportHeader1 }
     * 
     */
    public MoneyMarketReportHeader1 createMoneyMarketReportHeader1() {
        return new MoneyMarketReportHeader1();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link MmsrMessageType }
     * 
     */
    public MmsrMessageType createMmsrMessageType() {
        return new MmsrMessageType();
    }

    /**
     * Create an instance of {@link Party10Choice }
     * 
     */
    public Party10Choice createParty10Choice() {
        return new Party10Choice();
    }

    /**
     * Create an instance of {@link OptionDateOrPeriod1Choice }
     * 
     */
    public OptionDateOrPeriod1Choice createOptionDateOrPeriod1Choice() {
        return new OptionDateOrPeriod1Choice();
    }

    /**
     * Create an instance of {@link SupplementaryData1 }
     * 
     */
    public SupplementaryData1 createSupplementaryData1() {
        return new SupplementaryData1();
    }

    /**
     * Create an instance of {@link Party9Choice }
     * 
     */
    public Party9Choice createParty9Choice() {
        return new Party9Choice();
    }

    /**
     * Create an instance of {@link PartyIdentification42 }
     * 
     */
    public PartyIdentification42 createPartyIdentification42() {
        return new PartyIdentification42();
    }

    /**
     * Create an instance of {@link MoneyMarketUnsecuredMarketStatisticalReportV02 }
     * 
     */
    public MoneyMarketUnsecuredMarketStatisticalReportV02 createMoneyMarketUnsecuredMarketStatisticalReportV02() {
        return new MoneyMarketUnsecuredMarketStatisticalReportV02();
    }

    /**
     * Create an instance of {@link NameAndLocation1 }
     * 
     */
    public NameAndLocation1 createNameAndLocation1() {
        return new NameAndLocation1();
    }

    /**
     * Create an instance of {@link Option12 }
     * 
     */
    public Option12 createOption12() {
        return new Option12();
    }

    /**
     * Create an instance of {@link OrganisationIdentification7 }
     * 
     */
    public OrganisationIdentification7 createOrganisationIdentification7() {
        return new OrganisationIdentification7();
    }

    /**
     * Create an instance of {@link FloatingRateNote2 }
     * 
     */
    public FloatingRateNote2 createFloatingRateNote2() {
        return new FloatingRateNote2();
    }

    /**
     * Create an instance of {@link CounterpartyIdentification3Choice }
     * 
     */
    public CounterpartyIdentification3Choice createCounterpartyIdentification3Choice() {
        return new CounterpartyIdentification3Choice();
    }

    /**
     * Create an instance of {@link PersonIdentificationSchemeName1Choice }
     * 
     */
    public PersonIdentificationSchemeName1Choice createPersonIdentificationSchemeName1Choice() {
        return new PersonIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link BusinessApplicationHeaderV01 }
     * 
     */
    public BusinessApplicationHeaderV01 createBusinessApplicationHeaderV01() {
        return new BusinessApplicationHeaderV01();
    }

    /**
     * Create an instance of {@link ActiveCurrencyAndAmount }
     * 
     */
    public ActiveCurrencyAndAmount createActiveCurrencyAndAmount() {
        return new ActiveCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BusinessApplicationHeaderV01 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:iso:std:iso:20022:tech:xs:head.001.001.01", name = "AppHdr")
    public JAXBElement<BusinessApplicationHeaderV01> createAppHdr(BusinessApplicationHeaderV01 value) {
        return new JAXBElement<BusinessApplicationHeaderV01>(_AppHdr_QNAME, BusinessApplicationHeaderV01 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MmsrMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MMSRMessage")
    public JAXBElement<MmsrMessageType> createMMSRMessage(MmsrMessageType value) {
        return new JAXBElement<MmsrMessageType>(_MMSRMessage_QNAME, MmsrMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:iso:std:iso:20022:tech:xs:auth.013.001.02", name = "Document")
    public JAXBElement<Document> createDocument(Document value) {
        return new JAXBElement<Document>(_Document_QNAME, Document.class, null, value);
    }

}
